# Predictive analysis project

# 1. Data preprocessing and exploration

## Import libraries

In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [38]:
dataset = pd.read_excel("C:/Users/anoua/Downloads/CreditBank.xlsx")

C:\Users\anoua\anaconda3\lib\site-packages\openpyxl\worksheet\_read_only.py:79: UserWarning: Unknown extension is not supported and will be removed
  for idx, row in parser.parse():
C:\Users\anoua\anaconda3\lib\site-packages\openpyxl\worksheet\_read_only.py:79: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():


In [39]:
dataset.head()

revenuAnnuel  autreRevenu      salaire   age  anneeTravaillee  \
0       29921.0            0  2493.416667  51.0             10.0   
1       22912.0          530  1379.333333  32.0              5.0   
2       15780.0            0  1315.000000  30.0              5.0   
3       31293.0          848  1759.750000  29.0              5.0   
4       14312.0            0  1192.666667  36.0             10.0   

   nbDernierCreditRefuse  nbDernierCreditQccepte  PersonnesEnCharge  \
0                    0.0                     1.0                1.0   
1                    3.0                     2.0                1.0   
2                    3.0                     0.0                2.0   
3                    2.0                     2.0                0.0   
4                    2.0                     2.0                2.0   

   RevenuNetMoyen  nbVoitures catgSocialePro statutSocial  \
0      831.138889           2        Titular       Single   
1      636.444444           1        Titular       Single   
2      438.333333           0        Titular       Single   
3      869.250000           1    Contractual       Single   
4      397.555556           1        Titular       Single   

             Residence secteurTravail   Decision  
0          House Owner         Others   Accepted  
1  Living with parents  Developpement   Accepted  
2  Living with parents    Agriculture    Refused  
3  Living with parents         Others   Accepted  
4          House Owner       Handwork  Tolerated

In [40]:
dataset.shape

(172, 15)

In [41]:
dataset.tail()

revenuAnnuel  autreRevenu      salaire   age  anneeTravaillee  \
167        9807.0            0   817.250000  62.0             20.0   
168       15682.0            0  1306.833333  22.0              2.0   
169        9122.0            0   760.166667  25.0              2.0   
170        9703.0            0   808.583333  31.0              5.0   
171       17936.0            0  1494.666667  45.0              2.0   

     nbDernierCreditRefuse  nbDernierCreditQccepte  PersonnesEnCharge  \
167                    1.0                     2.0                2.0   
168                    4.0                     2.0                1.0   
169                    3.0                     0.0                3.0   
170                    2.0                     1.0                1.0   
171                    1.0                     0.0                2.0   

     RevenuNetMoyen  nbVoitures catgSocialePro statutSocial  \
167      272.416667           1        Retired      Married   
168      435.611111           0    Contractual       Single   
169      253.388889           0    Contractual       Single   
170      269.527778           1        Titular       Single   
171      498.222222           1    Contractual      Married   

               Residence     secteurTravail Decision  
167          Float Owner          Education  Refused  
168  Living with parents      Developpement  Refused  
169          House Owner  Telecommunication  Refused  
170  Living with parents           Commerce  Refused  
171          House Owner    Public Services  Refused

In [42]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172 entries, 0 to 171
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   revenuAnnuel            172 non-null    float64
 1   autreRevenu             172 non-null    int64  
 2   salaire                 171 non-null    float64
 3   age                     171 non-null    float64
 4   anneeTravaillee         171 non-null    float64
 5   nbDernierCreditRefuse   171 non-null    float64
 6   nbDernierCreditQccepte  171 non-null    float64
 7   PersonnesEnCharge       170 non-null    float64
 8   RevenuNetMoyen          171 non-null    float64
 9   nbVoitures              172 non-null    int64  
 10  catgSocialePro          171 non-null    object 
 11  statutSocial            169 non-null    object 
 12  Residence               170 non-null    object 
 13  secteurTravail          170 non-null    object 
 14  Decision                172 non-null    ob

In [43]:
dataset.isnull().sum()

revenuAnnuel              0
autreRevenu               0
salaire                   1
age                       1
anneeTravaillee           1
nbDernierCreditRefuse     1
nbDernierCreditQccepte    1
PersonnesEnCharge         2
RevenuNetMoyen            1
nbVoitures                0
catgSocialePro            1
statutSocial              3
Residence                 2
secteurTravail            2
Decision                  0
dtype: int64

In [44]:
dataset.describe()

revenuAnnuel  autreRevenu      salaire         age  anneeTravaillee  \
count    172.000000   172.000000   171.000000  171.000000       171.000000   
mean   19074.761628    84.581395  1513.783138   42.192982         6.321637   
std     6915.620548   214.930968   511.367373   14.823001         5.414202   
min        0.000000     0.000000   701.500000   20.000000         1.000000   
25%    13953.000000     0.000000  1087.166667   29.500000         2.000000   
50%    17984.500000     0.000000  1478.083333   41.000000         5.000000   
75%    25091.500000     0.000000  1956.666667   53.500000        10.000000   
max    37536.000000   871.000000  2493.416667   77.000000        20.000000   

       nbDernierCreditRefuse  nbDernierCreditQccepte  PersonnesEnCharge  \
count             171.000000              171.000000         170.000000   
mean                2.122807                1.040936           1.858824   
std                 1.329354                0.814261           1.360064   
min                 0.000000                0.000000           0.000000   
25%                 1.000000                0.000000           1.000000   
50%                 2.000000                1.000000           2.000000   
75%                 3.000000                2.000000           3.000000   
max                 4.000000                2.000000           4.000000   

       RevenuNetMoyen  nbVoitures  
count      171.000000  172.000000  
mean       530.568389    1.052326  
std        192.435776    0.668983  
min          0.000000    0.000000  
25%        384.027778    1.000000  
50%        500.916667    1.000000  
75%        698.583333    1.000000  
max       1042.666667    3.000000

In [48]:
dataset.describe(include=['object'])

catgSocialePro statutSocial    Residence secteurTravail Decision
count             171          169          170            170      172
unique              3            2            3              9        3
top           Titular       Single  House Owner      Education  Refused
freq              100           93           82             27       84

In [49]:
dataset['Residence'].unique()

array(['House Owner', 'Living with parents', 'Float Owner', nan],
      dtype=object)

In [50]:
dataset['Residence'].value_counts()

House Owner            82
Float Owner            48
Living with parents    40
Name: Residence, dtype: int64

## Input variables and target

In [51]:
x = dataset.iloc[:,0:14]
y = dataset.iloc[:,14]

In [52]:
x.head()

revenuAnnuel  autreRevenu      salaire   age  anneeTravaillee  \
0       29921.0            0  2493.416667  51.0             10.0   
1       22912.0          530  1379.333333  32.0              5.0   
2       15780.0            0  1315.000000  30.0              5.0   
3       31293.0          848  1759.750000  29.0              5.0   
4       14312.0            0  1192.666667  36.0             10.0   

   nbDernierCreditRefuse  nbDernierCreditQccepte  PersonnesEnCharge  \
0                    0.0                     1.0                1.0   
1                    3.0                     2.0                1.0   
2                    3.0                     0.0                2.0   
3                    2.0                     2.0                0.0   
4                    2.0                     2.0                2.0   

   RevenuNetMoyen  nbVoitures catgSocialePro statutSocial  \
0      831.138889           2        Titular       Single   
1      636.444444           1        Titular       Single   
2      438.333333           0        Titular       Single   
3      869.250000           1    Contractual       Single   
4      397.555556           1        Titular       Single   

             Residence secteurTravail  
0          House Owner         Others  
1  Living with parents  Developpement  
2  Living with parents    Agriculture  
3  Living with parents         Others  
4          House Owner       Handwork

In [53]:
y.head()

0     Accepted
1     Accepted
2      Refused
3     Accepted
4    Tolerated
Name: Decision, dtype: object

In [54]:
type(x)

pandas.core.frame.DataFrame

## convert dataframe to numpy

In [55]:
x = x.values #return the numpy representation of x
y = y.values

In [56]:
type(x)

numpy.ndarray

In [57]:
x.dtype

dtype('O')

In [58]:
x[0:5,:]

array([[29921.0, 0, 2493.4166666666665, 51.0, 10.0, 0.0, 1.0, 1.0,
        831.1388888888888, 2, 'Titular', 'Single', 'House Owner',
        'Others'],
       [22912.0, 530, 1379.3333333333333, 32.0, 5.0, 3.0, 2.0, 1.0,
        636.4444444444445, 1, 'Titular', 'Single', 'Living with parents',
        'Developpement'],
       [15780.0, 0, 1315.0, 30.0, 5.0, 3.0, 0.0, 2.0, 438.3333333333333,
        0, 'Titular', 'Single', 'Living with parents', 'Agriculture'],
       [31293.0, 848, 1759.75, 29.0, 5.0, 2.0, 2.0, 0.0, 869.25, 1,
        'Contractual', 'Single', 'Living with parents', 'Others'],
       [14312.0, 0, 1192.6666666666667, 36.0, 10.0, 2.0, 2.0, 2.0,
        397.5555555555556, 1, 'Titular', 'Single', 'House Owner',
        'Handwork']], dtype=object)

## Encoding categorical data

In [59]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [66]:
x[:,11] = label.fit_transform(x[:,11]) #normalisation, transform categorcal data to numerical data
x[:,12] = label.fit_transform(x[:,12])
x[:,13] = label.fit_transform(x[:,13])
x[:,10] = label.fit_transform(x[:,10])

In [69]:
y = label.fit_transform(y)

In [73]:
y

array([0, 0, 1, 0, 2, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 2, 2, 0, 1, 1, 2, 2, 1, 1, 0, 1, 0, 1, 1, 1, 2, 2, 2, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 1, 1, 1,
       2, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 0, 0, 1, 2, 2, 0, 2, 1, 0, 0,
       1, 2, 0, 0, 0, 0, 2, 1, 1, 2, 0, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       2, 0, 2, 1, 2, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 0, 2, 1, 1, 0, 2, 2, 0, 2, 1, 0,
       0, 1, 2, 0, 0, 0, 0, 2, 1, 1, 2, 0, 2, 1, 1, 1, 1, 1])

In [74]:
x[0:10,:]

array([[29921.0, 0, 2493.4166666666665, 51.0, 10.0, 0.0, 1.0, 1.0,
        831.1388888888888, 2, 2, 1, 1, 6],
       [22912.0, 530, 1379.3333333333333, 32.0, 5.0, 3.0, 2.0, 1.0,
        636.4444444444445, 1, 2, 1, 2, 2],
       [15780.0, 0, 1315.0, 30.0, 5.0, 3.0, 0.0, 2.0, 438.3333333333333,
        0, 2, 1, 2, 0],
       [31293.0, 848, 1759.75, 29.0, 5.0, 2.0, 2.0, 0.0, 869.25, 1, 0, 1,
        2, 6],
       [14312.0, 0, 1192.6666666666667, 36.0, 10.0, 2.0, 2.0, 2.0,
        397.5555555555556, 1, 2, 1, 1, 4],
       [22381.0, 0, 1865.0833333333333, 49.0, 2.0, 0.0, 1.0, 3.0,
        621.6944444444445, 2, 2, 0, 0, 8],
       [37536.0, 760, 2368.0, 27.0, 10.0, 4.0, 1.0, 1.0,
        1042.6666666666667, 1, 2, 1, 1, 9],
       [14259.0, 0, 1188.25, 31.0, 5.0, 1.0, 1.0, 0.0, 396.0833333333333,
        2, 2, 1, 1, 3],
       [16479.0, 328, 1045.25, 60.0, 20.0, 2.0, 0.0, 1.0, 457.75, 1, 1,
        0, 0, 2],
       [25441.0, 0, 2120.0833333333335, 32.0, 5.0, 0.0, 1.0, 1.0,
        706.6944444

## Splitting dataset into train and test sets

In [75]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state =0) #0.2 est la proportion de la base de test
#random state =0 pour fixer le choix aléatoire de la partie x_train et x_test

In [76]:
print ('x_train Shape=', x_train.shape) # taille de la partie x_train
print ('x_test Shape=', x_test.shape) # taille de la partie x_test
print ('y_train Shape=', y_train.shape) # taille de la partie y_train
print ('y_test Shape=', y_test.shape) # taille de la partie y_test

x_train Shape= (137, 14)
x_test Shape= (35, 14)
y_train Shape= (137,)
y_test Shape= (35,)


In [77]:
print ('taux de demandes dans toute la base: ', y.mean())
print ('taux de demandes dans toute Y_train: ', y_train.mean())
print ('taux de demandes dans toute Y_train: ', y_test.mean())

taux de demandes dans toute la base:  0.9069767441860465
taux de demandes dans toute Y_train:  0.9051094890510949
taux de demandes dans toute Y_train:  0.9142857142857143


In [78]:
x_test[0:5,:]

array([[18033.0, 0, 1502.75, 29.0, 2.0, 4.0, 1.0, 2.0, 500.9166666666667,
        0, 2, 0, 1, 8],
       [16901.0, 0, 1408.4166666666667, 50.0, 2.0, 3.0, 0.0, 3.0,
        469.47222222222223, 0, 0, 1, 0, 5],
       [8677.0, 0, 723.0833333333334, 66.0, 20.0, 3.0, 0.0, 1.0,
        241.0277777777778, 1, 1, 0, 1, 3],
       [14840.0, 0, 1236.6666666666667, 61.0, 2.0, 3.0, 1.0, 0.0,
        412.22222222222223, 0, 2, 0, 1, 2],
       [28728.0, 0, 2394.0, 42.0, 10.0, 0.0, 2.0, 4.0, 798.0, 1, 2, 1, 2,
        1]], dtype=object)