In [2]:
import pandas as pd #manipuler les dataframe
import numpy as np#manipuler des tableaux numpy
import warnings#ingorer les warnings
warnings.filterwarnings('ignore')

# read dataset to pandas dataframe

In [16]:
#read dataset
dataset=pd.read_csv('Churn_Modelling.csv')

In [17]:
#extraire 5 lignes de la base
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [18]:
#dimension
dataset.shape

(10000, 14)

In [19]:
#informations sur les colonnes
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


# input variables and target

In [20]:
#input variables and target
x=dataset.iloc[:,3:13] #toutes les lignes et de la  colonne  3(i) jusqu'a colonne 12(j)cad [i:j+1] (Rq:1ere colonne dindice 0 a part le id incremental )
y=dataset.iloc[:,13:14]#toutes les lignes et la colonne 13 cas y prend la 13eme colonne

In [21]:
#affichier les x
x.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [22]:
#affichier les y
y.head()

Exited
0       1
1       0
2       1
3       0
4       0

In [23]:
type(x)

pandas.core.frame.DataFrame

In [24]:
type(y)

pandas.core.frame.DataFrame

# convert dataframe to numpy array
#### (manipuler une matrcice  )

In [25]:
#convert dataframe to numpy array(manipuler une matrcice  )
x=x.values
y=y.values

In [26]:
# pour verifer le changement du type vers numpy (matrice)
type(x)

numpy.ndarray

In [27]:
type(y)

numpy.ndarray

In [28]:
#affichage les 10 1ere lignes tous les colonnes:cest une matrice du differente type
x[0:10,:]

array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [645, 'Spain', 'Male', 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [822, 'France', 'Male', 50, 7, 0.0, 2, 1, 1, 10062.8],
       [376, 'Germany', 'Female', 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [501, 'France', 'Male', 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [684, 'France', 'Male', 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

# encoding categorical data 
#### partie indespensable pour passer au partie modeling

In [15]:
#LabelEncader : permet de numérise une colonne par ordre alphabétique des catégories
from sklearn.preprocessing import LabelEncoder #
label =LabelEncoder()

In [16]:
x[:,1]=label.fit_transform(x[:,1])#numeriser toutes les lignes de la colonne 1 

In [17]:
#affichages des 10 1ere lignes tous les colonnes pour voir m'encodage de la colonne 1
x[0:10,:]

array([[619, 0, 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 2, 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 0, 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 0, 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 2, 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [645, 2, 'Male', 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [822, 0, 'Male', 50, 7, 0.0, 2, 1, 1, 10062.8],
       [376, 1, 'Female', 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [501, 0, 'Male', 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [684, 0, 'Male', 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

In [18]:
x[:,2]=label.fit_transform(x[:,2]) #numeriser toutes les lignes de la colonne 2

In [19]:
#affichages des 10 1ere lignes tous les colonnes pour voir m'encodage de la colonne 2
x[0:10,:]

array([[619, 0, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 2, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 0, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 0, 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 2, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [645, 2, 1, 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [822, 0, 1, 50, 7, 0.0, 2, 1, 1, 10062.8],
       [376, 1, 0, 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [501, 0, 1, 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [684, 0, 1, 27, 2, 134603.88, 1, 1, 1, 71725.73]], dtype=object)

# splitting dataset into train and test sets 
##### (division data patie train 80% et patie test 20%)

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=0) #0.2 est la proportion de la partie test
#random_state role fixer la partie pour une proprotion fixe cad aletoire fixe

In [21]:
X_train

array([[667, 2, 0, ..., 1, 0, 163830.64],
       [427, 1, 1, ..., 1, 1, 57098.0],
       [535, 0, 0, ..., 1, 0, 185630.76],
       ...,
       [738, 0, 1, ..., 1, 0, 181429.87],
       [590, 2, 0, ..., 1, 1, 148750.16],
       [623, 1, 0, ..., 1, 0, 118855.26]], dtype=object)

In [22]:
#pour voir la difference entre la presence de l'attribut random_state et la non presence 
#from sklearn.model_selection import train_test_split
#X_train,X_test,y_train,y_test= train_test_split(x,y,test_size=0.2)

In [23]:
#X_train

In [24]:
#dimension de chaque partie train et test 
print('X_train shape=',X_train.shape)#taille de la partie x_train
print('X_test shape=',X_test.shape)#taille de la partie x_test
print('Y_train shape=',y_train.shape)#taille de la partie y_train
print('y_test shape=',y_test.shape)#taille de la partie y_test


X_train shape= (8000, 10)
X_test shape= (2000, 10)
Y_train shape= (8000, 1)
y_test shape= (2000, 1)


In [25]:
#verifer la distribution des 0 et 1 dans toute la base : la base d'entrainement et la base de test 
print('taux de churn dans toute la base:',y.mean())
print('taux de churn dans toute y_train:',y_train.mean())
print('taux de churn dans toute y_test:',y_test.mean())



taux de churn dans toute la base: 0.2037
taux de churn dans toute y_train: 0.204
taux de churn dans toute y_test: 0.2025


# feature scaling
##### (normalisation toute les variable entre [0,1]ou bien la standarisation ) pour faire un equilibre cad mettre un echelle 

In [26]:
#from sklearn.processing import MinMaxScaler pour normalisation 
#appliquer une normalisation
from sklearn.preprocessing import StandardScaler #standarisation 
scaler=StandardScaler()
#si on utilise des algo calcul distance comme K-NN on utilise des donnees standarise 
#sinon pas besoin on peut utilise les donnees normal ou les srandarise aussi

In [27]:
#fit:calcul
#transform :transformation
x_train_sc= scaler.fit_transform(X_train)#on crée une copie de x_train(calcul et transformation)
x_test_sc=scaler.transform(X_test)#on crée une copie de x_test(transformation seulement)

In [28]:
x_train_sc[0,:]

array([ 0.16958176,  1.51919821, -1.09168714, -0.46460796,  0.00666099,
       -1.21571749,  0.8095029 ,  0.64259497, -1.03227043,  1.10643166])

In [29]:
X_train[0,:]

array([667, 2, 0, 34, 5, 0.0, 2, 1, 0, 163830.64], dtype=object)

# k-NN implementer le modele

In [30]:
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors=5)

In [31]:
knn.fit(x_train_sc,y_train)#placer les points et les colorier 
#entrainer le modele sur les données standariser x_train_sc/y_train

KNeighborsClassifier()

In [32]:
y_pred_knn= knn.predict(x_test_sc) #rendre un vecteur 

In [33]:
print(X_test[0:10,:]) #affichage les 10 1ere instances de la base 

[[597 1 0 35 8 131101.04 1 1 1 192852.67]
 [523 0 0 40 2 102967.41 1 1 0 128702.1]
 [706 2 0 42 8 95386.82 1 1 1 75732.25]
 [788 0 1 32 4 112079.58 1 0 0 89368.59]
 [706 1 1 38 5 163034.82 2 1 1 135662.17]
 [670 2 0 57 3 175575.95 2 1 0 99061.75]
 [590 2 1 34 0 65812.35 2 0 1 160346.3]
 [636 2 0 29 6 157576.47 2 1 1 101102.39]
 [598 0 0 64 9 0.0 1 0 1 13181.37]
 [456 0 0 63 1 165350.61 2 0 0 140758.07]]


In [34]:
print(x_test_sc[0:10,:]) #affichage

[[-0.55204276  0.3131264  -1.09168714 -0.36890377  1.04473698  0.8793029
  -0.92159124  0.64259497  0.9687384   1.61085707]
 [-1.31490297 -0.89294542 -1.09168714  0.10961719 -1.031415    0.42972196
  -0.92159124  0.64259497 -1.03227043  0.49587037]
 [ 0.57162971  1.51919821 -1.09168714  0.30102557  1.04473698  0.30858264
  -0.92159124  0.64259497  0.9687384  -0.42478674]
 [ 1.41696129 -0.89294542  0.91601335 -0.65601634 -0.33936434  0.57533623
  -0.92159124 -1.55619021 -1.03227043 -0.18777657]
 [ 0.57162971  0.3131264   0.91601335 -0.08179119  0.00666099  1.38961097
   0.8095029   0.64259497  0.9687384   0.61684179]
 [ 0.20050853  1.51919821 -1.09168714  1.73658844 -0.68538967  1.5900207
   0.8095029   0.64259497 -1.03227043 -0.01930192]
 [-0.62420521  1.51919821  0.91601335 -0.46460796 -1.72346566 -0.1640232
   0.8095029  -1.55619021  0.9687384   1.04587113]
 [-0.14999481  1.51919821 -1.09168714 -0.94312892  0.35268632  1.30238547
   0.8095029   0.64259497  0.9687384   0.01616599]
 [-

In [35]:
#for i in range(10)
#print()

In [36]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [37]:
print('confusion matrix knn\n',confusion_matrix(y_test,y_pred_knn))
print('accuracy knn',accuracy_score(y_test,y_pred_knn))     

confusion matrix knn
 [[1496   99]
 [ 232  173]]
accuracy knn 0.8345


In [38]:
from sklearn.metrics import recall_score,precision_score
print('recall knn',recall_score(y_test,y_pred_knn))
print('precision knn',precision_score(y_test,y_pred_knn))

recall knn 0.4271604938271605
precision knn 0.6360294117647058


In [39]:
#print('classification knn',classification_report(y_test,y_pred_knn))
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.87      0.94      0.90      1595
           1       0.64      0.43      0.51       405

    accuracy                           0.83      2000
   macro avg       0.75      0.68      0.71      2000
weighted avg       0.82      0.83      0.82      2000



In [40]:
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
for k in(3,4,5,6,7,8,9,10,11,12,13):
    n_neighbors=k
    print("k=",k)
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(x_train_sc,y_train)
    y_pred_knn= knn.predict(x_test_sc)
    print('accuracy knn',accuracy_score(y_test,y_pred_knn))  

k= 3
accuracy knn 0.824
k= 4
accuracy knn 0.834
k= 5
accuracy knn 0.8345
k= 6
accuracy knn 0.8425
k= 7
accuracy knn 0.841
k= 8
accuracy knn 0.844
k= 9
accuracy knn 0.841
k= 10
accuracy knn 0.847
k= 11
accuracy knn 0.8475
k= 12
accuracy knn 0.843
k= 13
accuracy knn 0.8465


In [45]:
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
max=0
for k in range(3,14):
    n_neighbors=k
    #print("k=",k)
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(x_train_sc,y_train)
    y_pred_knn= knn.predict(x_test_sc)
    if accuracy_score(y_test,y_pred_knn) > max : 
        max = accuracy_score(y_test,y_pred_knn) 
        index= k
print(max)
print(index)
    #print('accuracy knn',accuracy_score(y_test,y_pred_knn))  

0.8475
11
